### PR TITLE
Update indexmap, bump MSRV

### PR DESCRIPTION
**Pull request by westy92**
Updating indexmap to the latest version. Bump MSRV.

### CODE REVIEW

**Comment by AngelicosPhosphoros** [comment]
Hi!
Thank you for pull request, I would merge it at the evening.

**Comment by AngelicosPhosphoros** [comment]
Please, make Miri tests run using last available nightly with Miri component available.

**Comment by westy92** [comment]
I updated the nightly date to the day that 1.63 came out - that should fix things.

**Comment by AngelicosPhosphoros** [comment]
@westy92
Thank you for your contribution!

**Comment by westy92** [comment]
You're welcome!

**Comment by AngelicosPhosphoros** [comment]
I released 0.4.2

**Comment by westy92** [comment]
@AngelicosPhosphoros thank you so much! 🎉

**Pull request merged**
